services:
  # Votre service PHP (l'application)
  app:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  # Le serveur Web qui expose le port 8080
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB:-app}",
          "-U",
          "${POSTGRES_USER:-app}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080" # On lie le port 8081 de ton PC au port 8080 interne d'Adminer
    depends_on:
      - database
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
